name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get short commit
        id: vars
        run: echo "::set-output name=short_commit::$(git rev-parse --short HEAD)"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository | toLowerCase() }}:latest, ghcr.io/${{ github.repository | toLowerCase() }}:${{ github.event.release.tag_name }}-${{ steps.vars.outputs.short_commit }}

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.AZURE_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push to Azure Container Registry
        if: always()
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ vars.AZURE_REGISTRY }}/${{ github.repository | toLowerCase() }}:latest, ${{ vars.AZURE_REGISTRY }}/${{ github.repository | toLowerCase() }}:${{ github.event.release.tag_name }}-${{ steps.vars.outputs.short_commit }}
